name: Linters
on:
  pull_request:
    branches:
      - master

jobs:
  commitsar:
    name: Commitsar
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Commitsar Action
        uses: docker://commitsar/commitsar:0.7.0
